### ISSUE TITLE
Wrong use of setParameterValue and addParameterValue of Class CubismModel

### ISSUE THREAD

**Issue by Zhao-YinGang** [Live2D/CubismJavaSamples#5]
Wrong code:
  model.addParameterValue(idParamAngleX, dragX * 30); // -30から30の値を加える
  model.addParameterValue(idParamAngleY, dragY * 30);
  model.addParameterValue(idParamAngleZ, dragX * dragY * (-30));

... ...

Correct use
  model.setParameterValue(idParamAngleX, dragX * 30);
  model.setParameterValue(idParamAngleY, dragY * 30);
  model.setParameterValue(idParamAngleZ, dragX * dragY * (-30));

**Comment by Zhao-YinGang** [comment]
// com.live2d.sdk.cubism.framework.effect.CubismBreath

    public void updateParameters(CubismModel model, float deltaTimeSeconds) {
        userTimeSeconds += deltaTimeSeconds;
        final float t = userTimeSeconds * 2.0f * PI;

        for (int i = 0; i < breathParameters.size(); i++) {
            BreathParameterData breathData = breathParameters.get(i);

            final float value = breathData.offset + (breathData.peak * sinF(t / breathData.cycle));

            /* error  use
            model.addParameterValue(
                breathData.parameterId,
                value,
                breathData.weight); */
         // Correct use
              model.setParameterValue(
                breathData.parameterId,
                value,
                breathData.weight); 
        }
    }

**Comment by wada-at-live2d-com** [comment]
@Zhao-YinGang 

I am very sorry for the delay in replying to you.
Thank you for reporting the issue.

Now, regarding the point you reported, the parameter is intentionally set with addParameterValue.
Using addParameterValue will add the specified value to the current value. Therefore, it is possible to reflect effects such as breathing and eye tracking while taking advantage of motion and other movements.
If you use setParameterValue, it will overwrite the parameter if it is already used in motion. This is effective if you want to ignore the motion, etc. However, in the section you pointed out, we are using addParameterValue because we would like to use an expression that adds the parameter value.

Please also see this article about adding, multiplying, and overwriting parameters.
[https://docs.live2d.com/en/cubism-sdk-manual/expression/#:~:text=Differences in expression due to different arithmetic](https://docs.live2d.com/en/cubism-sdk-manual/expression/#:~:text=Differences%20in%20expression%20due%20to%20different%20arithmetic)

Thank you in advance.
